spring:
  application:
    name: eureka
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      default-property-inclusion: non_null
server:
  port: 8761 #启动端口
#  compression:
#      enabled: true
#      mime-types: application/json,application/xml,text/html,text/xml,text/plain
#      min-response-size: 2048
eureka:
  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    hostname: localhost
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
#    lease-renewal-interval-in-seconds: 30
#    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
#             defaultZone: http://${security.user.name}:${security.user.password}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/${spring.application.name}/
  server:
    enable-self-preservation: false    # 关闭 Eureka 的自我保护模式
endpoints:
  shutdown:
    enabled: true

info:
  name: 注册中心
  desc: 注册中心是所有接口的主入口
