spring:
  application:
    name: eureka
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      default-property-inclusion: non_null
server:
  port: 8761 #启动端口
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: false
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/${spring.application.name}/
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false    # 关闭 Eureka 的自我保护模式
info:
  name: 注册中心
  desc: 注册中心是所有接口的主入口
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS