spring:
  profiles:
    active: dev
    include: swagger
  datasource:
    url: jdbc:mysql://localhost:3306/test?useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: hukaijia
    password: Hukaijia.110
    type: com.alibaba.druid.pool.DruidDataSource
