spring:
  profiles:
    active: dev
    include: swagger
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: hukaijia
    password: Hukaijia.110

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadata-map:
      management:
        context-path: /actuator
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    ip-address: localhost
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
