apiVersion: v1
kind: Namespace
metadata:
  name: triumph
---
apiVersion: v1
kind: Service
metadata:
  namespace: triumph
  name: eureka
  labels:
    app: eureka
spec:
  ports:
  - name: http-eureka
    nodePort: 30081
    port: 8761
    protocol: TCP
    targetPort: 80
  selector:
    app: eureka
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: triumph
  name: eureka
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: registry.cn-hangzhou.aliyuncs.com/hukaijia/eureka:1.0.0 #镜像地址
        imagePullPolicy: Always
        ports:
        - containerPort: 9071
        - containerPort: 5005            #镜像拉去下来推到本地机器上
        env:
        - name: LNAG
          value: en_US.UTF-8
