apiVersion: v1
kind: Namespace
metadata:
  name: triumph
---
apiVersion: v1
kind: Service
metadata:
  namespace: triumph
  name: business
  labels:
    app: business
spec:
  ports:
  - name: http-business
    nodePort: 30082
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: business
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: triumph
  name: business
  labels:
    app: business
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business
  template:
    metadata:
      labels:
        app: business
    spec:
      containers:
      - name: business
        image: registry.cn-hangzhou.aliyuncs.com/hukaijia/business:1.0.0          #aliyun私有镜像地址
        imagePullPolicy: Never   #使用本地镜像
#        imagePullPolicy: Always   #拉取镜像
        ports:
        - containerPort: 8761
        - containerPort: 5005            #镜像拉去下来推到本地机器上
        env:
        - name: LNAG
          value: en_US.UTF-8
