apiVersion: v1
kind: Namespace
metadata:
  name: triumph
---
apiVersion: v1
kind: Service
metadata:
  namespace: triumph
  name: business
  labels:
    app: business
spec:
  ports:
  - name: http-business
    nodePort: 31954
    port: 9001
    protocol: TCP
    targetPort: 80
  selector:
    app: business
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: triumph
  name: business
  labels:
    app: business
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business
  template:
    metadata:
      labels:
        app: business
    spec:
      containers:
      - name: business
        image: billy98/nginx-prometheus-metrics:latest          #镜像地址
        imagePullPolicy: Always
        ports:
        - name: http-metrics
          containerPort: 9527
