#server:
#  servlet:
#    context-path: /ts
info:
  app:
    version: 2.1.1
    name: spring-boot-business
management:
  security:
    enabled: false
#prometheus+grafana+springboot2监控集成配置
#  metrics:
#    export:
#      prometheus:
#        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
#      base-path: /ts
  endpoint:
    health:
      show-details: ALWAYS
#  server:
#    servlet:
#      context-path: /ts
# prometheus+grafana+springboot2监控集成配置
spring:
  application:
    name: business-service
  profiles:
    active: @spring.profiles.active@
  jackson:
    serialization.write_dates_as_timestamps: true
  mvc:
    favicon:
      enabled: false
  devtools:
    restart:
      enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    platform: postgres
#    url: jdbc:postgresql://192.168.0.150:5432/postgres_test
#    username: postgres
#    password: drore1!
    # druid 数据库连接池配置
    druid:
      driver-class-name: org.postgresql.Driver
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
#      validation-query: SELECT 1 FROM DUAL
#      validation-query-timeout: 60000
#      test-on-borrow: false
#      test-on-return: false
#      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 100000
    # druid 数据库连接池配置
    # druid web配置 WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#        exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
    # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
#        allow: 127.0.0.1
#        deny: 192.168.32.139  #访问黑名单
     # 配置StatFilter
#      filter:
#        stat:
#          db-type: postgresql
#          log-slow-sql: true
#          slow-sql-millis: 5000
#        wall:
#          enabled: true
#          db-type: postgresql
#          config:
#            delete-allow: false
#            drop-table-allow: false

server:
  port: 9001
  session:
    cookie:
      http-only: true
    timeout: 36000
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.accumulate.business.entity
  typeEnumsPackage: com.accumulate.business.entity.enums
  global-config:
  #    # 数据库相关配置
    db-config:
  #      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: uuid
  #      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
  #      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除配置
  #      logic-delete-value: 0
  #      logic-not-delete-value: 1
  #      db-type: h2
    #刷新mapper 调试神器
  #    refresh: true
  # 原生配置
  #  configuration:
  #    map-underscore-to-camel-case: true
  #    cache-enabled: false
  ##logging
  #logging:
  #  level: warn
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

