spring:
  profiles:
    active: dev
    include: swagger
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.0.150:5432/postgres_test
    username: postgres
    password: drore1!
  redis:
    host: 192.168.0.150
    password:
    database: 3
    port: 6379
    timeout: 3000s
    jedis:
      pool:
        max-active: 1000
        max-wait: 60000
        max-idle: 400
        testOnBorrow: true
        testOnReturn: true

#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 10
##    spring-admin
#    health-check-url-path: /actuator/health
#  client:
#    registryFetchIntervalSeconds: 5
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
#    spring-admin
    metadata-map:
      management:
        context-path: /actuator
        port: 9001  #设置健康的port 设定特定的访问端口  重要
    health-check-url: http://192.168.123.83:9001/actuator/health
    status-page-url: http://192.168.123.83:9001/actuator/info
    home-page-url: http://192.168.123.83:9001/
    prefer-ip-address: true
    ip-address: 192.168.123.83   #设置健康的ip
#    non-secure-port-enabled: true
#    non-secure-port: 31943
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
