spring:
  profiles:
    active: dev
    include: swagger
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.0.150:5432/postgres_test
    username: postgres
    password: drore1!
  redis:
    host: 192.168.0.150
    password:
    database: 3
    port: 6379
    timeout: 3000s
    jedis:
      pool:
        max-active: 1000
        max-wait: 60000
        max-idle: 400
        testOnBorrow: true
        testOnReturn: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
#    spring-admin
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
