server:
  servlet:
    context-path: /ts
spring:
  profiles:
    active: prod
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres.drore-db:5432/drore_saas
    username: postgres
    password: drore1!

  # Redis
  redis:
    host: redis.drore-db
    password:
    # 数据库索引 默认0
    database: 4
    port: 6379
    timeout: 3000s
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
#    spring-admin
    metadata-map:
      management:
        context-path: /ts/actuator
        port: 30085
    health-check-url: http://118.31.17.205:30085/ts/actuator/health
    status-page-url: http://118.31.17.205:30085/ts/actuator/info
    home-page-url: http://118.31.17.205:30085/ts/
    prefer-ip-address: true
    ip-address: 118.31.17.205
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://118.31.17.205:8761/eureka/